#install.packages("renv")
library("renv")

#install.packages("tidyverse")
library("tidyverse")
#install.packages("sf")
library("sf")
#install.packages("janitor")
library("janitor")
#install.packages("mapview")
library("mapview")
library("ggplot2")
#install.packages("tidycensus")
library("tidycensus")
#install.packages("bigrquery")
library("bigrquery")


#renv::snapshot()
renv::activate()
